Makefile, README.md, pkg/controllers/nodeclaim/garbagecollection/controller.go, pkg/controllers/nodeclaim/garbagecollection/controller_test.go, pkg/controllers/nodeclaim/tagging/controller.go, pkg/controllers/nodeclaim/tagging/controller_test.go
=> fix race condition

README.md, cmd/controller/main.go
=> fix controller ctx + docs

charts/templates/role.yaml, pkg/cloudprovider/cloudprovider.go, pkg/cloudprovider/ibm/client.go, pkg/cloudprovider/ibm/iks.go, pkg/cloudprovider/ibm/iks_test.go, pkg/controllers/controllers.go, pkg/providers/instance/instance.go
=> fix more rbac and instance id validation

main.go
=> fix injection pattern to follow upstream karpenter v1

.gitleaks.toml, charts/templates/deployment.yaml, charts/values.yaml, docs/README.md
=> feat add values to helm chart, update docs, add gitleaks.toml

pkg/cloudprovider/cloudprovider.go, pkg/providers/instance/instance.go, pkg/providers/instance/instance_test.go
=> fix nodeclaim cleanup

pkg/providers/bootstrap/provider.go, pkg/providers/bootstrap/provider_test.go, pkg/providers/bootstrap/types.go
=> fix iks detection

pkg/providers/instance/instance.go, pkg/providers/instance/instance_test.go
=> fix iks detection for real

charts/Chart.yaml
=> bump chart

.github/workflows/container-images.yaml, .github/workflows/go-test.yaml, .github/workflows/helm-publish.yaml, .github/workflows/helm-test.yaml, charts/Chart.yaml
=> fix workflow rules

.github/workflows/container-images.yaml, .ko.yaml, Dockerfile.base, Makefile, charts/Chart.yaml, pkg/cloudprovider/ibm/client.go, pkg/cloudprovider/ibm/iam.go, pkg/cloudprovider/ibm/iks.go, pkg/cloudprovider/ibm/iks_cli.go, pkg/cloudprovider/ibm/iks_cli_test.go, pkg/cloudprovider/ibm/iks_test.go
=> fix iks api cli fallback

charts/Chart.yaml, pkg/providers/common/types/token.go, pkg/providers/vpc/bootstrap/provider_test.go
=> fix endpoint discovery

.github/workflows/pages-deploy.yml, charts/crds/karpenter.ibm.sh_ibmnodeclasses.yaml, cmd/controller/main_test.go, mkdocs.yml, pkg/apis/v1alpha1/ibmnodeclass_types.go, pkg/cloudprovider/cloudprovider.go, pkg/cloudprovider/cloudprovider_test.go, pkg/controllers/integration_test.go, pkg/controllers/nodeclass/hash/controller.go, pkg/controllers/nodeclass/hash/controller_test.go
=> fix hash controller

charts/Chart.yaml, pkg/providers/common/types/token.go, pkg/providers/vpc/bootstrap/cloudinit.go, pkg/providers/vpc/bootstrap/provider.go
=> fix cloud init

charts/Chart.yaml, charts/templates/role.yaml, charts/values.yaml, pkg/controllers/controllers.go, pkg/controllers/nodeclass/hash/controller.go, pkg/providers/vpc/bootstrap/apiendpoint_test.go, pkg/providers/vpc/bootstrap/cloudinit.go, pkg/providers/vpc/bootstrap/provider.go, pkg/providers/vpc/bootstrap/provider_test.go
=> feat bootstrap with CA

Makefile, charts/Chart.yaml, docs/bootstrap-methods.md, docs/vpc-integration.md, pkg/providers/vpc/bootstrap/cloudinit.go
=> fix cni cloudinit

pkg/controllers/controllers.go, pkg/providers/vpc/bootstrap/apiendpoint_test.go, pkg/providers/vpc/bootstrap/provider.go, pkg/providers/vpc/bootstrap/provider_test.go, pkg/providers/vpc/instance/provider.go
=> fix node lebels in cloudinit

charts/Chart.yaml, pkg/providers/common/types/bootstrap.go, pkg/providers/vpc/bootstrap/cloudinit.go, pkg/providers/vpc/bootstrap/provider.go
=> fix cloudinit

charts/Chart.yaml, cmd/controller/main.go, main.go, pkg/cloudprovider/ibm/client.go, pkg/controllers/controllers.go, pkg/controllers/node/orphancleanup/controller.go, pkg/controllers/node/orphancleanup/controller_test.go, pkg/test/providers.go
=> improved orpahned instance lifecycling

charts/Chart.yaml, charts/values.yaml, pkg/controllers/nodeclaim/garbagecollection/controller.go, pkg/controllers/nodeclaim/garbagecollection/controller_test.go
=> feat remove node finalizer on cleanup

charts/Chart.yaml, pkg/providers/common/types/bootstrap.go, pkg/providers/vpc/bootstrap/cloudinit.go, pkg/providers/vpc/bootstrap/provider.go, pkg/providers/vpc/bootstrap/provider_test.go
=> feat: detect instance arch for cloudinit

charts/Chart.yaml, charts/values.yaml, pkg/cloudprovider/ibm/client.go, pkg/cloudprovider/ibm/iam.go, pkg/providers/vpc/bootstrap/cloudinit.go, pkg/providers/vpc/bootstrap/provider_test.go, pkg/providers/vpc/instance/provider.go
=> feat: redo cloudinit instance metadata at runtime

charts/Chart.yaml, charts/values.yaml, pkg/controllers/nodeclaim/registration/controller.go
=> fix: apply init labels on ready karp nodes

pkg/cloudprovider/ibm/iks_test.go, pkg/controllers/interruption/controller_test.go, pkg/controllers/nodeclaim/tagging/controller_test.go, pkg/controllers/providers/instancetype/controller_test.go, pkg/controllers/providers/pricing/controller_test.go, pkg/providers/common/image/resolver_test.go, pkg/providers/common/pricing/ibm_provider_test.go, pkg/providers/iks/workerpool/provider_simple_test.go, pkg/providers/vpc/instance/provider_test.go, pkg/providers/vpc/subnet/provider_test.go
=> add more tests

charts/crds/karpenter.ibm.sh_ibmnodeclasses.yaml, docs/iks-integration.md, docs/vpc-integration.md, pkg/apis/v1alpha1/ibmnodeclass_types.go
=> fix: crd validation rule + crd docs

charts/Chart.yaml, charts/crds/karpenter.ibm.sh_ibmnodeclasses.yaml, pkg/providers/vpc/instance/provider.go, pkg/providers/vpc/instance/provider_test.go
=> feat: security group features for VPC instance provider

charts/Chart.yaml
=> chore: bump chart version to v0.3.54

pkg/cloudprovider/cloudprovider.go, pkg/cloudprovider/events/events.go, pkg/cloudprovider/events/events_test.go
=> fix: nodeclass resolution events

.github/workflows/cleanup-nightly-builds.yaml, test/e2e/e2e_test.go
=> fix: ci e2e

pkg/controllers/nodeclass/autoplacement/controller.go, pkg/controllers/nodeclass/autoplacement/controller_test.go
=> fix: autoplacement validation issue

pkg/cache/cache.go, pkg/cache/lock_upgrade_test.go, pkg/cache/race_condition_test.go, pkg/cache/unavailable_offerings.go
=> fix: cache racecondition

pkg/cloudprovider/ibm/vpc.go, pkg/cloudprovider/ibm/vpc_test.go, pkg/providers/common/image/resolver_test.go, pkg/providers/vpc/instance/provider.go, pkg/providers/vpc/instance/provider_test.go, pkg/providers/vpc/instance/resource_cleanup_test.go
=> fix: resource cleanup

pkg/cloudprovider/ibm/vpc.go, pkg/cloudprovider/ibm/vpc_test.go, pkg/controllers/bootstrap/token_controller.go, pkg/controllers/bootstrap/token_controller_test.go, pkg/controllers/nodeclass/status/controller.go, pkg/controllers/nodeclass/status/controller_test.go, pkg/operator/options/options.go, pkg/operator/options/options_test.go, pkg/providers/common/image/resolver_test.go, pkg/providers/common/instancetype/instancetype.go, pkg/providers/common/instancetype/instancetype_test.go, pkg/providers/common/instancetype/provider_test.go, pkg/providers/common/pricing/ibm_provider.go, pkg/providers/common/pricing/ibm_provider_test.go, pkg/providers/vpc/instance/provider_test.go
=> Fix hardcoded regions

README.md
Removed old /docs path to karpenter-ibm.sh in README.md
=> Removed old /docs path to karpenter-ibm.sh in README.md

.gitattributes, .pre-commit-config.yaml
=> fix: linter corrupting crds

pkg/controllers/nodeclass/status/controller.go, pkg/controllers/nodeclass/status/controller_test.go
=> fix: validation in crd only

.github/workflows/e2e-tests-in-cluster.yaml
=> fix: e2e ci

pkg/providers/vpc/instance/provider.go
=> Feat deprecate primary netw

pkg/providers/vpc/instance/provider.go
=> feat: vpc constructor logging

pkg/providers/vpc/instance/provider.go
=> fix: vni debugging

docs/vpc-integration.md, go.mod, go.sum, pkg/cloudprovider/ibm/client.go, pkg/controllers/nodeclaim/garbagecollection/controller.go, pkg/providers/vpc/bootstrap/cloudinit.go, pkg/providers/vpc/bootstrap/provider_test.go, pkg/providers/vpc/instance/provider.go
=> Fix vni debugging

charts/templates/role.yaml, pkg/controllers/controllers.go, pkg/providers/common/types/bootstrap.go, pkg/providers/vpc/bootstrap/cloudinit.go, pkg/providers/vpc/bootstrap/provider.go
=> feat: detect k8s version

charts/Chart.yaml, charts/values.yaml
=> release v0.3.64

.github/workflows/e2e-tests-in-cluster.yaml, .github/workflows/e2e-tests-pr.yml
=> chore(e2e): increase timeout

charts/Chart.yaml, charts/values.yaml
=> chore: bump release version 0.3.68

charts/Chart.yaml, charts/values.yaml
=> chore(release): v0.3.69 bump chart

.github/workflows/e2e-tests-in-cluster.yaml, pkg/providers/vpc/instance/provider.go
=> fix(e2e): cleanup commands

.github/workflows/e2e-tests-in-cluster.yaml
=> fix(e2e): scheduled e2e tests not the same as pr

pkg/fake/iamapi_test.go, pkg/fake/iksapi.go, pkg/fake/iksapi_test.go, pkg/fake/vpcapi_test.go
=> feat(tests): add unit tests for fake

cmd/controller/main_test.go
=> feat(tests): add unit tests for cmd

.codecov.yml
=> chore(tests): add codecov config

docs/userdata-feature.md, pkg/controllers/providers/instancetype/instancetype_test.go
=> chore(docs): added userdata docs

README.md, docs/image-selection.md, examples/imageSelector-example.yaml, examples/userdata-example.yaml, pkg/providers/vpc/instance/provider_multiaz_test.go, scripts/generate-k8s-support-table.sh
=> chore(docs): update docs

charts/templates/role.yaml, pkg/controllers/controllers.go
=> fix(clusterrole): add pv and pvc apigroups to clusterrole
